-- Migration for menu_items table
-- Run this in Supabase SQL editor

create table menu_items (
    id bigint generated by default as identity primary key,
    name text not null,
    category text not null,
    description text,
    price text not null,
    photo_url text,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes for faster queries
create index idx_menu_items_category on menu_items(category);
create index idx_menu_items_active on menu_items(is_active);